### ISSUE TITLE
Contiunous Read Option or Way of detecting Tag Departure

### ISSUE THREAD

**Issue by rbsparrow** [gutierrezps/gwiot7941e#4]
Hi,

Great little library and works really well with the Uno I've got, however, is there a way to either:

1) Continously report the tag whilst it is in range?
or
2) Notify on the tag lewaving the range of the reader?

I need to develop something which can determine whether a tag is in place or not.  With the current setup I can only detect the arrival of the tag, but not it's departure.

Your thoughts on this would be greatly appreciated.

Regards
Russell

**Comment by gutierrezps** [comment]
Hi. Unfortunately this RFID reader module doesn't provide such capability. When a RFID tag is read, the module transmits the tag ID only once, and that's it. It's not a library limitation, it's how the module works. I have also probed all pins of the P2 header (8-pin) with a logic analyzer, and they didn't output anything when reading a tag.

The [RDM6300 reader](https://github.com/arduino12/rdm6300) is what you're looking for, because it keeps transmitting the tag ID while it's in range. The down side is that its antenna is not as good as the 7941E module, according to my basic testings.

**Comment by rbsparrow** [comment]
I was afraid that might be the case, but thank you very much for investigating.


Russell Bird
IT Director, Nimlok Limited
t: 01933 409409 | m: +44 07734964139
a: 45 Booth Drive, Wellingborough, NN8 6NL
We value your privacy. View our privacy policy www.nimlok.co.uk/privacy
 If you believe you are receiving this email in error please contact: ***@***.***
From: Gabriel Gutierrez ***@***.***>
Date: Friday, 12 March 2021 at 01:21
To: gutierrezps/gwiot7941e ***@***.***>
Cc: Russell Bird ***@***.***>, Author ***@***.***>
Subject: Re: [gutierrezps/gwiot7941e] Contiunous Read Option or Way of detecting Tag Departure (#4)

Hi. Unfortunately this RFID reader module doesn't provide such capability. When a RFID tag is read, the module transmits the tag ID only once, and that's it. It's not a library limitation, it's how the module works. I have also probed all pins of the P2 header (8-pin) with a logic analyzer, and they didn't output anything when reading a tag.

The RDM6300 reader<https://github.com/arduino12/rdm6300> is what you're looking for, because it keeps transmitting the tag ID while it's in range. The down side is that its antenna is not as good as the 7941E module, according to my basic testings.
