### ISSUE TITLE
Error if (softwareSerial_) softwareSerial_->end(); in compile

### ISSUE THREAD

**Issue by kauaenrico** [gutierrezps/gwiot7941e#5]
Hello!
I'm testing the module I bought... I copied the basic code from your github, but when I try to compile it, it gives an error in the library code.
Would you help me?

**Code used:**
```
#include <Gwiot7941e.h>
#define GWIOT_7941E_RX_PIN 4
Gwiot7941e gwiot7941e;
void setup()
{
    //...
    gwiot7941e.begin(GWIOT_7941E_RX_PIN);
    //...
}
void loop()
{
    //...
    if (gwiot7941e.update()) {
        Serial.println(gwiot7941e.getLastTagId(), HEX);
    }
    //...
}
```
**Error:**
![image](https://user-images.githubusercontent.com/74334182/198153773-be7936b6-fda3-4b34-9bd0-4ab75c8591d8.png)

**Comment by gutierrezps** [comment]
Hello Kauã!

It's been some time since I've worked with embedded software. I've downloaded the latest Arduino IDE legacy version (1.8.19), the latest ESP8266 Arduino core (3.0.2), selected the NodeMCU 1.0 board (as shown on your screenshot) and compiled the `read_to_serial` example without changing anything, and it worked.

![image](https://user-images.githubusercontent.com/5178460/199570069-f2d47786-18fb-4b79-a723-27ea1764d670.png)

![image](https://user-images.githubusercontent.com/5178460/199570294-eb6a6f2b-0633-4df7-9899-2d51bb21f07c.png)

Can you please check your ESP8266 Arduino core version? And also post the entire source code?

**Comment by kauaenrico** [comment]
Hello again! I reinstalled my Arduino IDE and the libraries for the ESP, and it worked perfectly! Thank you for your help!
